[project]
name = "airplane-track"
version = "0.1.0"
description = ""
authors = [
    {name = "Denys",email = "nikeenko89@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "pytest (>=9.0.3,<10.0.0)",
    "requests (>=2.34.2,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=26.3.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "mypy (>=2.1.0,<3.0.0)",
    "pytest (>=9.0.3,<10.0.0)",
    "types-requests (>=2.33.0.20260513,<3.0.0.0)"
]

[tool.pytest.ini_options]
pythonpath = ["."]
